//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string CoachTeam {
            get {
                return ResourceManager.GetString("CoachTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of termination.
        /// </summary>
        public static string ContractDateOfTermination {
            get {
                return ResourceManager.GetString("ContractDateOfTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract end date.
        /// </summary>
        public static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string ContractPerson {
            get {
                return ResourceManager.GetString("ContractPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract start date.
        /// </summary>
        public static string ContractStartDate {
            get {
                return ResourceManager.GetString("ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ContractTeam {
            get {
                return ResourceManager.GetString("ContractTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture.
        /// </summary>
        public static string Fixture {
            get {
                return ResourceManager.GetString("Fixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string FixtureAction {
            get {
                return ResourceManager.GetString("FixtureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string FixtureAwayTeam {
            get {
                return ResourceManager.GetString("FixtureAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string FixtureHomeTeam {
            get {
                return ResourceManager.GetString("FixtureHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick off.
        /// </summary>
        public static string FixtureKickOff {
            get {
                return ResourceManager.GetString("FixtureKickOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string FixturePeriod {
            get {
                return ResourceManager.GetString("FixturePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee.
        /// </summary>
        public static string FixtureReferee {
            get {
                return ResourceManager.GetString("FixtureReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string FixtureSeason {
            get {
                return ResourceManager.GetString("FixtureSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string FixtureState {
            get {
                return ResourceManager.GetString("FixtureState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more libraries.
        /// </summary>
        public static string GetMoreLibraries {
            get {
                return ResourceManager.GetString("GetMoreLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects..
        /// </summary>
        public static string GetMoreLibrariesText {
            get {
                return ResourceManager.GetString("GetMoreLibrariesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development..
        /// </summary>
        public static string GettingStartedText {
            get {
                return ResourceManager.GetString("GettingStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript..
        /// </summary>
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string PersonDOB {
            get {
                return ResourceManager.GetString("PersonDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string PersonFirstName {
            get {
                return ResourceManager.GetString("PersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string PersonFullName {
            get {
                return ResourceManager.GetString("PersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string PersonLastName {
            get {
                return ResourceManager.GetString("PersonLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string PlayerTeam {
            get {
                return ResourceManager.GetString("PlayerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee.
        /// </summary>
        public static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season ends.
        /// </summary>
        public static string SeasonEndDate {
            get {
                return ResourceManager.GetString("SeasonEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SeasonName {
            get {
                return ResourceManager.GetString("SeasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season begins.
        /// </summary>
        public static string SeasonStartDate {
            get {
                return ResourceManager.GetString("SeasonStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium.
        /// </summary>
        public static string Stadium {
            get {
                return ResourceManager.GetString("Stadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string StadiumAddress {
            get {
                return ResourceManager.GetString("StadiumAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StadiumName {
            get {
                return ResourceManager.GetString("StadiumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach.
        /// </summary>
        public static string TeamCoach {
            get {
                return ResourceManager.GetString("TeamCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string TeamPlayers {
            get {
                return ResourceManager.GetString("TeamPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium.
        /// </summary>
        public static string TeamStadium {
            get {
                return ResourceManager.GetString("TeamStadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Hosting.
        /// </summary>
        public static string WebHosting {
            get {
                return ResourceManager.GetString("WebHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily find a web hosting company that offers the right mix of features and price for your applications..
        /// </summary>
        public static string WebHostingText {
            get {
                return ResourceManager.GetString("WebHostingText", resourceCulture);
            }
        }
    }
}
