// <auto-generated />
namespace League.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Changestatustostate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changestatustostate));
        
        string IMigrationMetadata.Id
        {
            get { return "201411251145069_Change status to state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
