namespace League.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RenamedIDs : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Contracts", "Person_ID", "dbo.People");
            DropForeignKey("dbo.Teams", "Coach_ID", "dbo.People");
            DropForeignKey("dbo.Teams", "Stadium_ID", "dbo.Stadia");
            DropForeignKey("dbo.Contracts", "Team_ID", "dbo.Teams");
            DropForeignKey("dbo.Fixtures", "AwayTeam_ID", "dbo.Teams");
            DropForeignKey("dbo.Fixtures", "HomeTeam_ID", "dbo.Teams");
            DropForeignKey("dbo.Fixtures", "Referee_ID", "dbo.People");
            DropForeignKey("dbo.Fixtures", "Season_ID", "dbo.Seasons");
            DropForeignKey("dbo.FixtureStatistics", "Fixture_ID", "dbo.Fixtures");
            DropForeignKey("dbo.FixtureStatistics", "Player_ID", "dbo.People");
            DropForeignKey("dbo.FixtureStatus", "Fixture_ID", "dbo.Fixtures");
            DropForeignKey("dbo.AspNetUsers", "UserInfo_ID", "dbo.People");
            DropForeignKey("dbo.People", "Team_ID", "dbo.Teams");
            DropIndex("dbo.Contracts", new[] { "Person_ID" });
            DropIndex("dbo.Teams", new[] { "Coach_ID" });
            DropIndex("dbo.Teams", new[] { "Stadium_ID" });
            DropIndex("dbo.Contracts", new[] { "Team_ID" });
            DropIndex("dbo.Fixtures", new[] { "AwayTeam_ID" });
            DropIndex("dbo.Fixtures", new[] { "HomeTeam_ID" });
            DropIndex("dbo.Fixtures", new[] { "Referee_ID" });
            DropIndex("dbo.Fixtures", new[] { "Season_ID" });
            DropIndex("dbo.FixtureStatistics", new[] { "Fixture_ID" });
            DropIndex("dbo.FixtureStatistics", new[] { "Player_ID" });
            DropIndex("dbo.FixtureStatus", new[] { "Fixture_ID" });
            DropIndex("dbo.AspNetUsers", new[] { "UserInfo_ID" });
            DropIndex("dbo.People", new[] { "Team_ID" });
            AlterColumn("dbo.People", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.People", "ID", c => c.Int());
            AlterColumn("dbo.People", "Team_Id", c => c.Int());
            AlterColumn("dbo.Contracts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Contracts", "Person_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Contracts", "Team_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Teams", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Teams", "Stadium_Id", c => c.Int());
            AlterColumn("dbo.Stadia", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Fixtures", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Fixtures", "AwayTeam_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "HomeTeam_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "Referee_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "Season_Id", c => c.Int());
            AlterColumn("dbo.Seasons", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.FixtureStatistics", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.FixtureStatistics", "Fixture_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatistics", "Player_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatus", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.FixtureStatus", "Fixture_Id", c => c.Int());
            AlterColumn("dbo.AspNetUsers", "UserInfo_Id", c => c.Int());
            DropPrimaryKey("dbo.People");
            AddPrimaryKey("dbo.People", "Id");
            DropPrimaryKey("dbo.Contracts");
            AddPrimaryKey("dbo.Contracts", "Id");
            DropPrimaryKey("dbo.Teams");
            AddPrimaryKey("dbo.Teams", "Id");
            DropPrimaryKey("dbo.Stadia");
            AddPrimaryKey("dbo.Stadia", "Id");
            DropPrimaryKey("dbo.Fixtures");
            AddPrimaryKey("dbo.Fixtures", "Id");
            DropPrimaryKey("dbo.Seasons");
            AddPrimaryKey("dbo.Seasons", "Id");
            DropPrimaryKey("dbo.FixtureStatistics");
            AddPrimaryKey("dbo.FixtureStatistics", "Id");
            DropPrimaryKey("dbo.FixtureStatus");
            AddPrimaryKey("dbo.FixtureStatus", "Id");
            CreateIndex("dbo.Contracts", "Person_Id");
            CreateIndex("dbo.People", "Id");
            CreateIndex("dbo.Teams", "Stadium_Id");
            CreateIndex("dbo.Contracts", "Team_Id");
            CreateIndex("dbo.Fixtures", "AwayTeam_Id");
            CreateIndex("dbo.Fixtures", "HomeTeam_Id");
            CreateIndex("dbo.Fixtures", "Referee_Id");
            CreateIndex("dbo.Fixtures", "Season_Id");
            CreateIndex("dbo.FixtureStatistics", "Fixture_Id");
            CreateIndex("dbo.FixtureStatistics", "Player_Id");
            CreateIndex("dbo.FixtureStatus", "Fixture_Id");
            CreateIndex("dbo.AspNetUsers", "UserInfo_Id");
            CreateIndex("dbo.People", "Team_Id");
            AddForeignKey("dbo.Contracts", "Person_Id", "dbo.People", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "Id", "dbo.Teams", "Id");
            AddForeignKey("dbo.Teams", "Stadium_Id", "dbo.Stadia", "Id");
            AddForeignKey("dbo.Contracts", "Team_Id", "dbo.Teams", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Fixtures", "AwayTeam_Id", "dbo.Teams", "Id");
            AddForeignKey("dbo.Fixtures", "HomeTeam_Id", "dbo.Teams", "Id");
            AddForeignKey("dbo.Fixtures", "Referee_Id", "dbo.People", "Id");
            AddForeignKey("dbo.Fixtures", "Season_Id", "dbo.Seasons", "Id");
            AddForeignKey("dbo.FixtureStatistics", "Fixture_Id", "dbo.Fixtures", "Id");
            AddForeignKey("dbo.FixtureStatistics", "Player_Id", "dbo.People", "Id");
            AddForeignKey("dbo.FixtureStatus", "Fixture_Id", "dbo.Fixtures", "Id");
            AddForeignKey("dbo.AspNetUsers", "UserInfo_Id", "dbo.People", "Id");
            AddForeignKey("dbo.People", "Team_Id", "dbo.Teams", "Id");
            DropColumn("dbo.Teams", "Coach_ID");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Teams", "Coach_ID", c => c.Int());
            DropForeignKey("dbo.People", "Team_Id", "dbo.Teams");
            DropForeignKey("dbo.AspNetUsers", "UserInfo_Id", "dbo.People");
            DropForeignKey("dbo.FixtureStatus", "Fixture_Id", "dbo.Fixtures");
            DropForeignKey("dbo.FixtureStatistics", "Player_Id", "dbo.People");
            DropForeignKey("dbo.FixtureStatistics", "Fixture_Id", "dbo.Fixtures");
            DropForeignKey("dbo.Fixtures", "Season_Id", "dbo.Seasons");
            DropForeignKey("dbo.Fixtures", "Referee_Id", "dbo.People");
            DropForeignKey("dbo.Fixtures", "HomeTeam_Id", "dbo.Teams");
            DropForeignKey("dbo.Fixtures", "AwayTeam_Id", "dbo.Teams");
            DropForeignKey("dbo.Contracts", "Team_Id", "dbo.Teams");
            DropForeignKey("dbo.Teams", "Stadium_Id", "dbo.Stadia");
            DropForeignKey("dbo.People", "Id", "dbo.Teams");
            DropForeignKey("dbo.Contracts", "Person_Id", "dbo.People");
            DropIndex("dbo.People", new[] { "Team_Id" });
            DropIndex("dbo.AspNetUsers", new[] { "UserInfo_Id" });
            DropIndex("dbo.FixtureStatus", new[] { "Fixture_Id" });
            DropIndex("dbo.FixtureStatistics", new[] { "Player_Id" });
            DropIndex("dbo.FixtureStatistics", new[] { "Fixture_Id" });
            DropIndex("dbo.Fixtures", new[] { "Season_Id" });
            DropIndex("dbo.Fixtures", new[] { "Referee_Id" });
            DropIndex("dbo.Fixtures", new[] { "HomeTeam_Id" });
            DropIndex("dbo.Fixtures", new[] { "AwayTeam_Id" });
            DropIndex("dbo.Contracts", new[] { "Team_Id" });
            DropIndex("dbo.Teams", new[] { "Stadium_Id" });
            DropIndex("dbo.People", new[] { "Id" });
            DropIndex("dbo.Contracts", new[] { "Person_Id" });
            DropPrimaryKey("dbo.FixtureStatus");
            AddPrimaryKey("dbo.FixtureStatus", "ID");
            DropPrimaryKey("dbo.FixtureStatistics");
            AddPrimaryKey("dbo.FixtureStatistics", "ID");
            DropPrimaryKey("dbo.Seasons");
            AddPrimaryKey("dbo.Seasons", "ID");
            DropPrimaryKey("dbo.Fixtures");
            AddPrimaryKey("dbo.Fixtures", "ID");
            DropPrimaryKey("dbo.Stadia");
            AddPrimaryKey("dbo.Stadia", "ID");
            DropPrimaryKey("dbo.Teams");
            AddPrimaryKey("dbo.Teams", "ID");
            DropPrimaryKey("dbo.Contracts");
            AddPrimaryKey("dbo.Contracts", "ID");
            DropPrimaryKey("dbo.People");
            AddPrimaryKey("dbo.People", "ID");
            AlterColumn("dbo.AspNetUsers", "UserInfo_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatus", "Fixture_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatus", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.FixtureStatistics", "Player_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatistics", "Fixture_Id", c => c.Int());
            AlterColumn("dbo.FixtureStatistics", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Seasons", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Fixtures", "Season_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "Referee_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "HomeTeam_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "AwayTeam_Id", c => c.Int());
            AlterColumn("dbo.Fixtures", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Stadia", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Teams", "Stadium_Id", c => c.Int());
            AlterColumn("dbo.Teams", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Contracts", "Team_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Contracts", "Person_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Contracts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.People", "Team_Id", c => c.Int());
            AlterColumn("dbo.People", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.People", "Id", c => c.Int(nullable: false, identity: true));
            CreateIndex("dbo.People", "Team_ID");
            CreateIndex("dbo.AspNetUsers", "UserInfo_ID");
            CreateIndex("dbo.FixtureStatus", "Fixture_ID");
            CreateIndex("dbo.FixtureStatistics", "Player_ID");
            CreateIndex("dbo.FixtureStatistics", "Fixture_ID");
            CreateIndex("dbo.Fixtures", "Season_ID");
            CreateIndex("dbo.Fixtures", "Referee_ID");
            CreateIndex("dbo.Fixtures", "HomeTeam_ID");
            CreateIndex("dbo.Fixtures", "AwayTeam_ID");
            CreateIndex("dbo.Contracts", "Team_ID");
            CreateIndex("dbo.Teams", "Stadium_ID");
            CreateIndex("dbo.Teams", "Coach_ID");
            CreateIndex("dbo.Contracts", "Person_ID");
            AddForeignKey("dbo.People", "Team_ID", "dbo.Teams", "ID");
            AddForeignKey("dbo.AspNetUsers", "UserInfo_ID", "dbo.People", "ID");
            AddForeignKey("dbo.FixtureStatus", "Fixture_ID", "dbo.Fixtures", "ID");
            AddForeignKey("dbo.FixtureStatistics", "Player_ID", "dbo.People", "ID");
            AddForeignKey("dbo.FixtureStatistics", "Fixture_ID", "dbo.Fixtures", "ID");
            AddForeignKey("dbo.Fixtures", "Season_ID", "dbo.Seasons", "ID");
            AddForeignKey("dbo.Fixtures", "Referee_ID", "dbo.People", "ID");
            AddForeignKey("dbo.Fixtures", "HomeTeam_ID", "dbo.Teams", "ID");
            AddForeignKey("dbo.Fixtures", "AwayTeam_ID", "dbo.Teams", "ID");
            AddForeignKey("dbo.Contracts", "Team_ID", "dbo.Teams", "ID", cascadeDelete: true);
            AddForeignKey("dbo.Teams", "Stadium_ID", "dbo.Stadia", "ID");
            AddForeignKey("dbo.Teams", "Coach_ID", "dbo.People", "ID");
            AddForeignKey("dbo.Contracts", "Person_ID", "dbo.People", "ID", cascadeDelete: true);
        }
    }
}
